name: policy-update

on:
  push:
    branches:
      - main
      - test1

permissions:
      contents: write

jobs:
  bash-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.json$' | xargs)"

      - name: policy files changed
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: generate mermaid images
        run:  for i in ${{ steps.getfile.outputs.files }}; do bash mermaid.sh $i; done

      - name: Git changes
        run: |
          git add .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
          git pull
          git push origin main

      - name: Run Bash script
        run:  for i in ${{ steps.getfile.outputs.files }}; do bash run.sh $i; done