name: policy-update

on:
  push:
    branches:
      - main
      - test1

permissions:
      contents: write

jobs:
  bash-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: get changed files
        id: getfile
        shell: bash
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.json$' | xargs)"

      - name: policy files changed
        shell: bash
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: generate mermaid images
        shell: bash
        run:  |
          echo "Show default environment variable"
          chmod +x mermaid.sh
          for i in ${{ steps.getfile.outputs.files }}; do ./mermaid.sh $i; done

      - name: Run Bash script
        shell: bash
        run:  for i in ${{ steps.getfile.outputs.files }}; do bash run.sh $i; done